site_name: loglib
site_description: An online library for learning AI from the ground up.
site_url: https://mcembalest.github.io/loglib
nav:
  - Home:
    - 'Welcome': index.md
  - Applications:
    - 'Applications': applications/index.md
    - 'Customer Segmentation': applications/customer-segmentation.md
    - 'Document Analysis': applications/document-analysis.md
    - 'Fraud Detection': applications/fraud-detection.md
  - Programming:
    - 'Programming': programming/index.md
    - 'APIs': programming/apis.md
    - 'Terminals': programming/terminals.md
    - 'Python': programming/python.md
    - 'JavaScript': programming/javascript.md
  - Math:
    - 'Math': math/index.md
    - 'Linear Algebra': math/linear-algebra.md
    - 'Calculus': math/calculus.md
    - 'Probability and Statistics': math/probability-and-statistics.md
  - Chronology:
    - 'Chronology': chronology/index.md
    - '1600s': chronology/1600s.md
    - '1700s': chronology/1700s.md
    - '1800s': chronology/1800s.md
    - '1900s': chronology/1900s.md
    - '2000-2010': chronology/2000-2010.md
    - '2010-2020': chronology/2010-2020.md
    - '2020-Present': chronology/2020-present.md
  - Glossary:
    - 'Glossary': glossary/index.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
